### ISSUE TITLE
Finish Migrating Language Picker

### ISSUE THREAD

**Issue by ressonix** [ressonix/rockylinux.org-gatsby#2]
This issue is being created for tracking since I need to be in bed :p. I've brought over the drop-down, but it needs some fine-tuning. For instance, the current implementation will route English to /en, which doesn't exist. I'm not too familiar with how `gatsby-plugin-i18n` and `gatsby-theme-i18n` handle this and will do some further research, but of course contributions are welcome!

Ideally, we'd want the drop-down to feel as similar as possible to the existing implementation from the live Hugo version of the site.

**Comment by utkusaridede** [comment]
I'm gonna work on it :+1:
